"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { FormEvent, useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createSupabaseClient } from "@/lib/supabase";

type Employee={id:string;updated_at:string;employee_number:string;full_name:string;email:string|null;mobile_number:string|null;birth_date:string|null;address:string|null;department:string|null;position_title:string|null;hire_date:string|null;employment_type:string;employment_status:string;probation_months:number|null;regularization_due_date:string|null;contract_start_date:string|null;contract_end_date:string|null;contract_term_months:number|null;pay_frequency:string;rate_type:string;basic_rate:number|null;sss_number:string|null;philhealth_number:string|null;pagibig_number:string|null;tin_number:string|null;thirteenth_month_enabled:boolean;sss_enabled:boolean;philhealth_enabled:boolean;pagibig_enabled:boolean};
type Master={id:string;category:string;code:string;label:string;numeric_value:number|null};

export default function EditEmployeePage(){
  const {id}=useParams<{id:string}>(),router=useRouter(),db=useRef<SupabaseClient|null>(null);
  const [employee,setEmployee]=useState<Employee|null>(null),[masters,setMasters]=useState<Master[]>([]),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  const options=(category:string)=>masters.filter(item=>item.category===category);
  useEffect(()=>{const client=createSupabaseClient();db.current=client;client.auth.getUser().then(async({data})=>{if(!data.user)return router.replace("/login");const [{data:record,error},{data:list}]=await Promise.all([client.from("employees").select("*").eq("id",id).single(),client.from("hr_master_list_items").select("id,category,code,label,numeric_value").eq("is_active",true).order("sort_order")]);if(error)return setMessage(error.message);setEmployee(record as Employee);setMasters((list||[]) as Master[]);});},[id,router]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const f=new FormData(e.currentTarget),status=String(f.get("employment_status"));const payload={full_name:f.get("full_name"),email:f.get("email")||null,mobile_number:f.get("mobile_number")||null,birth_date:f.get("birth_date")||null,address:f.get("address")||null,department:f.get("department")||null,position_title:f.get("position_title")||null,hire_date:f.get("hire_date")||null,employment_type:f.get("employment_type"),employment_status:status,active:status==="active",kiosk_enabled:status==="active",probation_months:Number(f.get("probation_months"))||null,regularization_due_date:f.get("regularization_due_date")||null,contract_start_date:f.get("contract_start_date")||null,contract_end_date:f.get("contract_end_date")||null,contract_term_months:Number(f.get("contract_term_months"))||null,pay_frequency:f.get("pay_frequency"),rate_type:f.get("rate_type"),basic_rate:Number(f.get("basic_rate"))||null,sss_number:f.get("sss_number")||null,philhealth_number:f.get("philhealth_number")||null,pagibig_number:f.get("pagibig_number")||null,tin_number:f.get("tin_number")||null,thirteenth_month_enabled:f.get("thirteenth_month_enabled")==="on",sss_enabled:f.get("sss_enabled")==="on",philhealth_enabled:f.get("philhealth_enabled")==="on",pagibig_enabled:f.get("pagibig_enabled")==="on",updated_at:new Date().toISOString()};const {data,error}=await db.current!.from("employees").update(payload).eq("id",id).select("*").single();setSaving(false);if(error)return setMessage(error.message);setEmployee(data as Employee);setMessage("Employee record updated successfully.");}
  if(!employee)return <main className="admin-page"><div className="admin-content">{message||"Loading employee…"}</div></main>;
  return <main className="admin-page"><header className="admin-top"><div className="brand login-brand"><b>P</b> PulseHR</div><div><a href="/employees">← Employee directory</a><a href="/settings/master-lists">Master lists</a></div></header><div className="edit-employee-page admin-content"><div className="admin-title"><small>EMPLOYEE RECORD</small><h1>Edit {employee.full_name}</h1><p>{employee.employee_number} · Update details without losing attendance or payroll history.</p></div>{message&&<div className="login-message">{message}</div>}
    <form className="card employee-form edit-record-form" onSubmit={save} key={employee.id+employee.updated_at}><fieldset><legend>Identity and contact</legend><div className="form-grid"><label>Full name<input name="full_name" required defaultValue={employee.full_name}/></label><label>Employee ID<input value={employee.employee_number} readOnly disabled/></label><label>Email<input name="email" type="email" defaultValue={employee.email||""}/></label><label>Mobile number<input name="mobile_number" defaultValue={employee.mobile_number||""}/></label><label>Birth date<input name="birth_date" type="date" defaultValue={employee.birth_date||""}/></label><label className="wide">Address<textarea name="address" defaultValue={employee.address||""}/></label></div></fieldset>
      <fieldset><legend>Employment and lifecycle status</legend><div className="form-grid"><label>Department<select name="department" defaultValue={employee.department||""}><option value="">Unassigned</option>{options("department").map(i=><option key={i.id} value={i.label}>{i.label}</option>)}</select></label><label>Position<select name="position_title" defaultValue={employee.position_title||""}><option value="">Unassigned</option>{options("position").map(i=><option key={i.id} value={i.label}>{i.label}</option>)}</select></label><label>Hire date<input name="hire_date" type="date" defaultValue={employee.hire_date||""}/></label><label>Employment classification<select name="employment_type" defaultValue={employee.employment_type}>{options("employment_type").map(i=><option key={i.id} value={i.code}>{i.label}</option>)}</select></label><label>Employee status<select name="employment_status" defaultValue={employee.employment_status}>{options("employee_status").map(i=><option key={i.id} value={i.code}>{i.label}</option>)}</select></label><label>Probation months<input name="probation_months" type="number" min="1" max="6" defaultValue={employee.probation_months||""}/></label><label>Regularization review<input name="regularization_due_date" type="date" defaultValue={employee.regularization_due_date||""}/></label><label>Contract start<input name="contract_start_date" type="date" defaultValue={employee.contract_start_date||""}/></label><label>Contract end<input name="contract_end_date" type="date" defaultValue={employee.contract_end_date||""}/></label><label>Contract months<select name="contract_term_months" defaultValue={employee.contract_term_months||""}><option value="">Not applicable</option>{options("contract_term").map(i=><option key={i.id} value={Number(i.numeric_value)}>{i.label}</option>)}</select></label></div><p className="legal-note">Inactive, retired, on-leave, and separated employees cannot use kiosk attendance. Their historical records remain available.</p></fieldset>
      <fieldset><legend>Pay and government benefits</legend><div className="form-grid"><label>Pay frequency<select name="pay_frequency" defaultValue={employee.pay_frequency}>{options("pay_frequency").map(i=><option key={i.id} value={i.code}>{i.label}</option>)}</select></label><label>Rate basis<select name="rate_type" defaultValue={employee.rate_type}>{options("rate_type").map(i=><option key={i.id} value={i.code}>{i.label}</option>)}</select></label><label>Basic rate (PHP)<input name="basic_rate" type="number" min="0" step="0.01" defaultValue={employee.basic_rate||""}/></label><label>SSS number<input name="sss_number" defaultValue={employee.sss_number||""}/></label><label>PhilHealth number<input name="philhealth_number" defaultValue={employee.philhealth_number||""}/></label><label>Pag-IBIG MID<input name="pagibig_number" defaultValue={employee.pagibig_number||""}/></label><label>TIN<input name="tin_number" defaultValue={employee.tin_number||""}/></label></div><div className="benefit-grid edit-benefits"><label><input type="checkbox" name="thirteenth_month_enabled" defaultChecked={employee.thirteenth_month_enabled}/> 13th-month pay</label><label><input type="checkbox" name="sss_enabled" defaultChecked={employee.sss_enabled}/> SSS</label><label><input type="checkbox" name="philhealth_enabled" defaultChecked={employee.philhealth_enabled}/> PhilHealth</label><label><input type="checkbox" name="pagibig_enabled" defaultChecked={employee.pagibig_enabled}/> Pag-IBIG</label></div></fieldset><div className="edit-actions"><a href="/employees" className="outline">Cancel</a><button className="primary" disabled={saving}>{saving?"Saving changes…":"Save employee changes"}</button></div></form>
  </div></main>;
}
