"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {createSupabaseClient} from "@/lib/supabase";
type Employee=Record<string,unknown>&{id:string;employee_number:string;full_name:string;email:string|null;mobile_number:string|null;birth_date:string|null;address:string|null;department:string|null;position_title:string|null;hire_date:string|null;employment_type:string;employment_status:string;regularization_due_date:string|null;contract_start_date:string|null;contract_end_date:string|null;contract_term_months:number|null;pay_frequency:string;rate_type:string;basic_rate:number|null;sss_number:string|null;philhealth_number:string|null;pagibig_number:string|null;tin_number:string|null;thirteenth_month_enabled:boolean;sss_enabled:boolean;philhealth_enabled:boolean;pagibig_enabled:boolean};
type Master={category:string;code:string;label:string};type Leave={id:string;leave_name:string;annual_days:number|null;entitlement_kind:string;enabled:boolean};type Attendance={id:string;event_type:string;occurred_at:string;location_unavailable:boolean};
export default function EmployeeProfilePage(){const {id}=useParams<{id:string}>(),router=useRouter();const [employee,setEmployee]=useState<Employee|null>(null),[masters,setMasters]=useState<Master[]>([]),[leaves,setLeaves]=useState<Leave[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[message,setMessage]=useState("");
useEffect(()=>{const client=createSupabaseClient();client.auth.getUser().then(async({data})=>{if(!data.user)return router.replace("/login");const [{data:record,error},{data:list},{data:leaveRows},{data:events}]=await Promise.all([client.from("employees").select("*").eq("id",id).single(),client.from("hr_master_list_items").select("category,code,label"),client.from("employee_leave_entitlements").select("id,leave_name,annual_days,entitlement_kind,enabled").eq("employee_id",id).order("leave_name"),client.from("kiosk_attendance_events").select("id,event_type,occurred_at,location_unavailable").eq("employee_id",id).order("occurred_at",{ascending:false}).limit(10)]);if(error)return setMessage(error.message);setEmployee(record as Employee);setMasters((list||[]) as Master[]);setLeaves((leaveRows||[]) as Leave[]);setAttendance((events||[]) as Attendance[]);});},[id,router]);
const label=(category:string,code:string)=>masters.find(i=>i.category===category&&i.code===code)?.label||code.replaceAll("_"," "),value=(content:unknown)=>content===null||content===undefined||content===""?"—":String(content);const benefit=(name:string,enabled:boolean,idNumber?:string|null)=><div className={enabled?"profile-benefit enabled":"profile-benefit"}><b>{enabled?"✓":"—"} {name}</b><small>{idNumber||(enabled?"Enabled":"Not enrolled")}</small></div>;if(!employee)return <main className="admin-page"><div className="admin-content">{message||"Loading employee profile…"}</div></main>;
return <main className="admin-page"><header className="admin-top"><div className="brand login-brand"><b>P</b> PulseHR</div><div><a href="/employees">← Employee directory</a><a href={`/employees/${id}`}>Edit employee</a></div></header><div className="employee-profile admin-content"><section className="profile-hero card"><div className="profile-avatar">{employee.full_name.split(" ").map(n=>n[0]).join("").slice(0,2).toUpperCase()}</div><div><small>EMPLOYEE PROFILE</small><h1>{employee.full_name}</h1><p>{employee.employee_number} · {employee.position_title||"Position unassigned"} · {employee.department||"Department unassigned"}</p></div><i className={`employee-status ${employee.employment_status}`}>{label("employee_status",employee.employment_status)}</i><a className="primary profile-edit" href={`/employees/${id}`}>Edit record</a></section>
<div className="profile-grid"><section className="card profile-section"><h2>Personal and contact</h2><dl><div><dt>Email</dt><dd>{value(employee.email)}</dd></div><div><dt>Mobile</dt><dd>{value(employee.mobile_number)}</dd></div><div><dt>Birth date</dt><dd>{value(employee.birth_date)}</dd></div><div className="wide"><dt>Address</dt><dd>{value(employee.address)}</dd></div></dl></section><section className="card profile-section"><h2>Employment</h2><dl><div><dt>Classification</dt><dd>{label("employment_type",employee.employment_type)}</dd></div><div><dt>Status</dt><dd>{label("employee_status",employee.employment_status)}</dd></div><div><dt>Hire date</dt><dd>{value(employee.hire_date)}</dd></div><div><dt>Regularization review</dt><dd>{value(employee.regularization_due_date)}</dd></div><div><dt>Contract start</dt><dd>{value(employee.contract_start_date)}</dd></div><div><dt>Contract end</dt><dd>{value(employee.contract_end_date)}</dd></div></dl></section><section className="card profile-section"><h2>Pay setup</h2><dl><div><dt>Pay frequency</dt><dd>{label("pay_frequency",employee.pay_frequency)}</dd></div><div><dt>Rate basis</dt><dd>{label("rate_type",employee.rate_type)}</dd></div><div><dt>Basic rate</dt><dd>{employee.basic_rate===null?"—":`₱${Number(employee.basic_rate).toLocaleString("en-PH",{minimumFractionDigits:2})}`}</dd></div><div><dt>Contract term</dt><dd>{employee.contract_term_months?`${employee.contract_term_months} months`:"—"}</dd></div></dl></section><section className="card profile-section"><h2>Government benefits</h2><div className="profile-benefits">{benefit("13th-month pay",employee.thirteenth_month_enabled)}{benefit("SSS",employee.sss_enabled,employee.sss_number)}{benefit("PhilHealth",employee.philhealth_enabled,employee.philhealth_number)}{benefit("Pag-IBIG",employee.pagibig_enabled,employee.pagibig_number)}{benefit("TIN",Boolean(employee.tin_number),employee.tin_number)}</div></section></div>
<section className="card profile-section profile-wide"><div className="section-head"><div><h2>Leave entitlements</h2><p>Current configured employee leave benefits</p></div></div><div className="profile-leaves">{leaves.length?leaves.map(leave=><div key={leave.id}><b>{leave.leave_name}</b><span>{leave.enabled?(leave.entitlement_kind==="statutory_event"?"Eligibility-based":`${leave.annual_days||0} days`):"Disabled"}</span></div>):<p>No leave entitlements configured.</p>}</div></section><section className="card profile-section profile-wide"><div className="section-head"><div><h2>Recent attendance</h2><p>Latest 10 kiosk attendance records</p></div><a href="/reports">Full report →</a></div><div className="profile-attendance head"><span>Action</span><span>Date and time</span><span>Location</span></div>{attendance.length?attendance.map(event=><div className="profile-attendance" key={event.id}><span>{event.event_type==="clock_in"?"Clock in":"Clock out"}</span><span>{new Date(event.occurred_at).toLocaleString("en-PH")}</span><span>{event.location_unavailable?"Flagged":"Captured"}</span></div>):<p className="profile-empty">No kiosk attendance recorded.</p>}</section></div></main>}
