"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createSupabaseClient } from "@/lib/supabase";

type Employee={id:string;employee_number:string;full_name:string;email:string|null;mobile_number:string|null;department:string|null;position_title:string|null;hire_date:string|null;employment_type:string;employment_status:string;pay_frequency:string;rate_type:string;basic_rate:number|null;regularization_due_date:string|null;contract_end_date:string|null};
type Alert={employee_id:string;full_name:string;alert_type:string;due_date:string;days_remaining:number};
type Policy={probation_months:number;contract_term_options:number[];default_pay_frequency:string};
type Master={id:string;category:string;code:string;label:string;numeric_value:number|null;metadata:Record<string,unknown>;is_default:boolean};

export default function EmployeesPage(){
  const router=useRouter(),db=useRef<SupabaseClient|null>(null);
  const [org,setOrg]=useState(""),[employees,setEmployees]=useState<Employee[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[masters,setMasters]=useState<Master[]>([]);
  const [policy,setPolicy]=useState<Policy>({probation_months:6,contract_term_options:[3,6,12],default_pay_frequency:"semi_monthly"});
  const [type,setType]=useState("probationary"),[hireDate,setHireDate]=useState(""),[contractMonths,setContractMonths]=useState(12);
  const [query,setQuery]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  const options=(category:string)=>masters.filter(item=>item.category===category);

  const load=useCallback(async(client:SupabaseClient,organizationId:string)=>{
    const [{data:staff},{data:notices},{data:settings},{data:list}]=await Promise.all([
      client.from("employees").select("id,employee_number,full_name,email,mobile_number,department,position_title,hire_date,employment_type,employment_status,pay_frequency,rate_type,basic_rate,regularization_due_date,contract_end_date").order("full_name"),
      client.from("employee_employment_alerts").select("employee_id,full_name,alert_type,due_date,days_remaining").lte("days_remaining",60).order("days_remaining"),
      client.from("employment_policy_settings").select("probation_months,contract_term_options,default_pay_frequency").eq("organization_id",organizationId).maybeSingle(),
      client.from("hr_master_list_items").select("id,category,code,label,numeric_value,metadata,is_default").eq("is_active",true).order("sort_order").order("label"),
    ]);
    setEmployees((staff||[]) as Employee[]);setAlerts((notices||[]) as Alert[]);setMasters((list||[]) as Master[]);
    if(settings)setPolicy(settings as Policy);
    const defaultType=(list as Master[]|null)?.find(i=>i.category==="employment_type"&&i.is_default);if(defaultType)setType(defaultType.code);
    const defaultTerm=(list as Master[]|null)?.find(i=>i.category==="contract_term"&&i.is_default);if(defaultTerm?.numeric_value)setContractMonths(defaultTerm.numeric_value);
  },[]);
  useEffect(()=>{const client=createSupabaseClient();db.current=client;client.auth.getUser().then(async({data})=>{if(!data.user)return router.replace("/login");const {data:p}=await client.from("profiles").select("organization_id").eq("id",data.user.id).single();if(!p)return setMessage("HR profile was not found.");setOrg(p.organization_id);await load(client,p.organization_id);});},[load,router]);
  const addMonths=(date:string,months:number)=>{const d=new Date(`${date}T00:00:00`);d.setMonth(d.getMonth()+months);return d.toISOString().slice(0,10)};
  const selectedType=options("employment_type").find(i=>i.code===type),requiresProbation=selectedType?.metadata.requires_probation===true||type==="probationary",requiresContract=selectedType?.metadata.requires_contract_end===true||type==="fixed_term";

  async function savePolicy(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),months=Number(f.get("probation_months")),pay=String(f.get("default_pay_frequency"));const terms=options("contract_term").map(i=>Number(i.numeric_value)).filter(Boolean);const {error}=await db.current!.from("employment_policy_settings").upsert({organization_id:org,probation_months:months,contract_term_options:terms,default_pay_frequency:pay,updated_at:new Date().toISOString()});if(error)return setMessage(error.message);setPolicy({probation_months:months,contract_term_options:terms,default_pay_frequency:pay});setMessage("Employment defaults saved.");}

  async function addEmployee(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const element=e.currentTarget,f=new FormData(element);
    const employeeNumber=String(f.get("employee_number")).trim().toUpperCase();
    const {data:existing,error:lookupError}=await db.current!.from("employees").select("id").eq("organization_id",org).eq("employee_number",employeeNumber).maybeSingle();
    if(lookupError){setSaving(false);return setMessage(lookupError.message)}let id=existing?.id,wasExisting=Boolean(existing);const start=String(f.get("hire_date"));
    if(!id){const {data:created,error:createError}=await db.current!.rpc("admin_create_employee",{p_employee_number:employeeNumber,p_full_name:f.get("full_name"),p_pin:f.get("pin"),p_kiosk_enabled:true,p_personal_enabled:false,p_selfie_required:true});if(createError){setSaving(false);return setMessage(createError.message.includes("duplicate key")?"That Employee ID already exists. Refresh the page and try saving again.":createError.message)}id=(created as {id:string}).id;wasExisting=false;}
    const {error:updateError}=await db.current!.from("employees").update({full_name:f.get("full_name"),email:f.get("email")||null,mobile_number:f.get("mobile_number")||null,birth_date:f.get("birth_date")||null,address:f.get("address")||null,department:f.get("department")||null,position_title:f.get("position_title")||null,hire_date:start,employment_type:type,employment_status:"active",pay_frequency:f.get("pay_frequency"),rate_type:f.get("rate_type"),basic_rate:Number(f.get("basic_rate"))||null,probation_months:requiresProbation?policy.probation_months:null,regularization_due_date:requiresProbation?addMonths(start,policy.probation_months):null,contract_start_date:requiresContract?start:null,contract_term_months:requiresContract?contractMonths:null,contract_end_date:requiresContract?addMonths(start,contractMonths):null,sss_number:f.get("sss_number")||null,philhealth_number:f.get("philhealth_number")||null,pagibig_number:f.get("pagibig_number")||null,tin_number:f.get("tin_number")||null,thirteenth_month_enabled:f.get("thirteenth_month_enabled")==="on",sss_enabled:f.get("sss_enabled")==="on",philhealth_enabled:f.get("philhealth_enabled")==="on",pagibig_enabled:f.get("pagibig_enabled")==="on",updated_at:new Date().toISOString()}).eq("id",id);
    if(updateError){setSaving(false);return setMessage(`Employee details were not saved: ${updateError.message}`)}
    const entitlements=options("leave_type").map(item=>({organization_id:org,employee_id:id,leave_code:item.code,leave_name:item.label,annual_days:item.metadata.entitlement_kind==="statutory_event"?null:Number(f.get(`leave_${item.id}`)||item.numeric_value||0),entitlement_kind:item.metadata.entitlement_kind==="statutory_event"?"statutory_event":"annual_credit",enabled:f.get(`enable_${item.id}`)==="on",effective_from:start}));
    const {error:leaveError}=entitlements.length?await db.current!.from("employee_leave_entitlements").upsert(entitlements,{onConflict:"employee_id,leave_code,effective_from"}):{error:null};setSaving(false);element.reset();setHireDate("");setMessage(leaveError?`Employee saved; leave setup needs attention: ${leaveError.message}`:wasExisting?"Existing employee record completed and updated.":"New employee details and entitlements saved.");await load(db.current!,org);
  }

  return <main className="admin-page"><header className="admin-top"><div className="brand login-brand"><b>P</b> PulseHR</div><div><a href="/">Dashboard</a><a href="/attendance">Attendance</a><a href="/reports">Reports</a><a href="/settings/master-lists">Master lists</a></div></header><div className="employee-master admin-content">
    <div className="admin-title"><small>PEOPLE ADMINISTRATION</small><h1>Employee master</h1><p>Employment terms, alerts, leave entitlements, payroll setup, and government benefits.</p></div>{message&&<div className="login-message">{message}</div>}
    {alerts.length>0&&<section className="alert-panel card"><h2>Upcoming employment actions</h2><div className="alert-list">{alerts.map(a=><div key={a.employee_id}><b>{a.full_name}</b><span>{a.alert_type==="regularization"?"Regularization review":"Contract renewal"} · {a.due_date}</span><em className={a.days_remaining<0?"late":""}>{a.days_remaining<0?`${Math.abs(a.days_remaining)} days overdue`:`${a.days_remaining} days left`}</em></div>)}</div></section>}
    <section className="employee-layout"><form className="card employee-form" onSubmit={addEmployee}><div className="form-title"><h2>Add complete employee record</h2><p>Dropdown choices come from HR Master Lists.</p></div>
      <fieldset><legend>Identity and contact</legend><div className="form-grid"><label>Full name<input name="full_name" required/></label><label>Employee ID<input name="employee_number" required/></label><label>Email<input name="email" type="email"/></label><label>Mobile number<input name="mobile_number"/></label><label>Birth date<input name="birth_date" type="date"/></label><label>Initial kiosk PIN<input name="pin" type="password" inputMode="numeric" pattern="[0-9]{4,8}" required/></label><label className="wide">Address<textarea name="address"/></label></div></fieldset>
      <fieldset><legend>Employment and pay</legend><div className="form-grid">
        <label>Department<select name="department"><option value="">Unassigned</option>{options("department").map(i=><option key={i.id} value={i.label}>{i.label}</option>)}</select></label>
        <label>Position<select name="position_title"><option value="">Unassigned</option>{options("position").map(i=><option key={i.id} value={i.label}>{i.label}</option>)}</select></label>
        <label>Hire/start date<input name="hire_date" type="date" required value={hireDate} onChange={e=>setHireDate(e.target.value)}/></label>
        <label>Classification<select name="employment_type" value={type} onChange={e=>setType(e.target.value)}>{options("employment_type").map(i=><option key={i.id} value={i.code}>{i.label}</option>)}</select></label>
        {requiresProbation&&<div className="calculated wide">Regularization review: {hireDate?addMonths(hireDate,policy.probation_months):`after ${policy.probation_months} months`}</div>}
        {requiresContract&&<label>Contract term<select value={contractMonths} onChange={e=>setContractMonths(Number(e.target.value))}>{options("contract_term").map(i=><option key={i.id} value={Number(i.numeric_value)}>{i.label}</option>)}</select></label>}
        <label>Pay frequency<select name="pay_frequency" defaultValue={options("pay_frequency").find(i=>i.is_default)?.code||policy.default_pay_frequency}>{options("pay_frequency").map(i=><option key={i.id} value={i.code}>{i.label}</option>)}</select></label>
        <label>Rate basis<select name="rate_type" defaultValue={options("rate_type").find(i=>i.is_default)?.code}>{options("rate_type").map(i=><option key={i.id} value={i.code}>{i.label}</option>)}</select></label>
        <label>Basic rate (PHP)<input name="basic_rate" type="number" min="0" step="0.01"/></label>
      </div></fieldset>
      <fieldset><legend>Philippine benefits</legend><div className="benefit-grid"><label><input type="checkbox" name="thirteenth_month_enabled" defaultChecked/> 13th-month pay</label><label><input type="checkbox" name="sss_enabled" defaultChecked/> SSS</label><label><input type="checkbox" name="philhealth_enabled" defaultChecked/> PhilHealth</label><label><input type="checkbox" name="pagibig_enabled" defaultChecked/> Pag-IBIG</label></div><div className="form-grid ids"><label>SSS number<input name="sss_number"/></label><label>PhilHealth number<input name="philhealth_number"/></label><label>Pag-IBIG MID<input name="pagibig_number"/></label><label>TIN<input name="tin_number"/></label></div><p className="legal-note">Statutory benefits are enabled by default. Disable only with a documented lawful exclusion.</p></fieldset>
      <fieldset><legend>Leave entitlements</legend><div className="leave-grid">{options("leave_type").map(item=>{const eventBased=item.metadata.entitlement_kind==="statutory_event";return <div key={item.id}><label><input type="checkbox" name={`enable_${item.id}`} defaultChecked={eventBased||type==="regular"}/> {item.label}</label>{eventBased?<span>Eligibility-based</span>:<input aria-label={`${item.label} days`} name={`leave_${item.id}`} type="number" min="0" step="0.5" defaultValue={item.numeric_value||0}/>}</div>})}</div></fieldset><button className="primary save-employee" disabled={saving}>{saving?"Saving employee…":"Save employee record"}</button>
    </form><aside className="policy-side card"><h2>Dynamic defaults</h2><p>Master-list options appear immediately in this form.</p><form onSubmit={savePolicy}><label>Probation period<select name="probation_months" defaultValue={policy.probation_months}>{[1,2,3,4,5,6].map(m=><option key={m} value={m}>{m} month{m>1?"s":""}</option>)}</select></label><label>Default pay frequency<select name="default_pay_frequency" defaultValue={policy.default_pay_frequency}>{options("pay_frequency").map(i=><option key={i.id} value={i.code}>{i.label}</option>)}</select></label><button className="primary">Save defaults</button></form><a className="manage-master-link" href="/settings/master-lists">Manage all master lists →</a><div className="policy-warning"><b>Legal guardrail</b><p>Probation is capped at six months. Existing employee terms are preserved when lists change.</p></div></aside></section>
    <section className="card admin-table employee-list"><div className="section-head"><div><h3>Complete employee directory</h3><p>{employees.length} records · edit employment, contact, pay, and status</p></div><input className="table-search" placeholder="Search any employee detail" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="employee-directory-scroll"><div className="employee-directory-tr head"><span>Employee</span><span>Contact</span><span>Role</span><span>Employment</span><span>Status</span><span>Pay</span><span>Dates</span><span>Action</span></div>{employees.filter(e=>`${e.full_name} ${e.employee_number} ${e.email||""} ${e.mobile_number||""} ${e.department||""} ${e.position_title||""} ${e.employment_status}`.toLowerCase().includes(query.toLowerCase())).map(e=><div className="employee-directory-tr" key={e.id}><span><b>{e.full_name}</b><small>{e.employee_number}</small></span><span>{e.email||"—"}<small>{e.mobile_number||"No mobile"}</small></span><span>{e.position_title||"—"}<small>{e.department||"Unassigned"}</small></span><span>{options("employment_type").find(i=>i.code===e.employment_type)?.label||e.employment_type}<small>{options("pay_frequency").find(i=>i.code===e.pay_frequency)?.label||e.pay_frequency}</small></span><span><i className={`employee-status ${e.employment_status}`}>{options("employee_status").find(i=>i.code===e.employment_status)?.label||e.employment_status}</i></span><span>{e.basic_rate!==null?`₱${Number(e.basic_rate).toLocaleString("en-PH")}`:"—"}<small>{e.rate_type||"No rate basis"}</small></span><span>{e.hire_date||"No hire date"}<small>{e.regularization_due_date||e.contract_end_date||"No next action"}</small></span><span><a className="edit-employee" href={`/employees/${e.id}`}>Edit</a></span></div>)}</div></section>
  </div></main>;
}
