"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createSupabaseClient } from "@/lib/supabase";

type Employee = { id:string; employee_number:string; full_name:string; department:string|null; position_title:string|null; employment_type:string; pay_frequency:string; regularization_due_date:string|null; contract_end_date:string|null };
type Alert = { employee_id:string; full_name:string; alert_type:string; due_date:string; days_remaining:number };
type Policy = { probation_months:number; contract_term_options:number[]; default_pay_frequency:string };
const leaves = [["VL","Vacation leave","5","annual_credit"],["SL","Sick leave","5","annual_credit"],["BL","Birthday leave","1","annual_credit"],["MAT","Maternity leave","","statutory_event"],["PAT","Paternity leave","","statutory_event"]] as const;

export default function EmployeesPage() {
  const router=useRouter(), db=useRef<SupabaseClient|null>(null);
  const [org,setOrg]=useState(""), [employees,setEmployees]=useState<Employee[]>([]), [alerts,setAlerts]=useState<Alert[]>([]);
  const [policy,setPolicy]=useState<Policy>({probation_months:6,contract_term_options:[3,6,12],default_pay_frequency:"semi_monthly"});
  const [type,setType]=useState("probationary"), [hireDate,setHireDate]=useState(""), [contractMonths,setContractMonths]=useState(12);
  const [query,setQuery]=useState(""), [message,setMessage]=useState(""), [saving,setSaving]=useState(false);

  const load=useCallback(async(client:SupabaseClient,organizationId:string)=>{
    const [{data:staff},{data:notices},{data:settings}]=await Promise.all([
      client.from("employees").select("id,employee_number,full_name,department,position_title,employment_type,pay_frequency,regularization_due_date,contract_end_date").order("full_name"),
      client.from("employee_employment_alerts").select("employee_id,full_name,alert_type,due_date,days_remaining").lte("days_remaining",60).order("days_remaining"),
      client.from("employment_policy_settings").select("probation_months,contract_term_options,default_pay_frequency").eq("organization_id",organizationId).maybeSingle()
    ]);
    setEmployees((staff||[]) as Employee[]); setAlerts((notices||[]) as Alert[]); if(settings)setPolicy(settings as Policy);
  },[]);
  useEffect(()=>{const client=createSupabaseClient();db.current=client;client.auth.getUser().then(async({data})=>{if(!data.user)return router.replace("/login");const {data:p}=await client.from("profiles").select("organization_id").eq("id",data.user.id).single();if(!p)return setMessage("HR profile was not found.");setOrg(p.organization_id);await load(client,p.organization_id);});},[load,router]);
  const addMonths=(date:string,months:number)=>{const d=new Date(`${date}T00:00:00`);d.setMonth(d.getMonth()+months);return d.toISOString().slice(0,10)};

  async function savePolicy(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),months=Number(f.get("probation_months")),terms=String(f.get("contract_terms")).split(",").map(Number).filter(n=>n>0&&n<=60),pay=String(f.get("default_pay_frequency"));const {error}=await db.current!.from("employment_policy_settings").upsert({organization_id:org,probation_months:months,contract_term_options:terms,default_pay_frequency:pay,updated_at:new Date().toISOString()});if(error)return setMessage(error.message);setPolicy({probation_months:months,contract_term_options:terms,default_pay_frequency:pay});setMessage("Employment defaults saved.");}

  async function addEmployee(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const element=e.currentTarget,f=new FormData(element);
    const {data:created,error:createError}=await db.current!.rpc("admin_create_employee",{p_employee_number:f.get("employee_number"),p_full_name:f.get("full_name"),p_pin:f.get("pin"),p_kiosk_enabled:true,p_personal_enabled:false,p_selfie_required:true});
    if(createError){setSaving(false);return setMessage(createError.message)} const id=(created as {id:string}).id,start=String(f.get("hire_date")),employmentType=String(f.get("employment_type"));
    const {error:updateError}=await db.current!.from("employees").update({email:f.get("email")||null,mobile_number:f.get("mobile_number")||null,birth_date:f.get("birth_date")||null,address:f.get("address")||null,department:f.get("department")||null,position_title:f.get("position_title")||null,hire_date:start,employment_type:employmentType,employment_status:"active",pay_frequency:f.get("pay_frequency"),rate_type:f.get("rate_type"),basic_rate:Number(f.get("basic_rate"))||null,probation_months:employmentType==="probationary"?policy.probation_months:null,regularization_due_date:employmentType==="probationary"?addMonths(start,policy.probation_months):null,contract_start_date:employmentType==="fixed_term"?start:null,contract_term_months:employmentType==="fixed_term"?contractMonths:null,contract_end_date:employmentType==="fixed_term"?addMonths(start,contractMonths):null,sss_number:f.get("sss_number")||null,philhealth_number:f.get("philhealth_number")||null,pagibig_number:f.get("pagibig_number")||null,tin_number:f.get("tin_number")||null,thirteenth_month_enabled:f.get("thirteenth_month_enabled")==="on",sss_enabled:f.get("sss_enabled")==="on",philhealth_enabled:f.get("philhealth_enabled")==="on",pagibig_enabled:f.get("pagibig_enabled")==="on",updated_at:new Date().toISOString()}).eq("id",id);
    if(updateError){setSaving(false);return setMessage(`Employee created, but details need attention: ${updateError.message}`)}
    const entitlements=leaves.map(([code,name,days,kind])=>({organization_id:org,employee_id:id,leave_code:code,leave_name:name,annual_days:kind==="annual_credit"?Number(f.get(`leave_${code}`)||days):null,entitlement_kind:kind,enabled:f.get(`enable_${code}`)==="on",effective_from:start}));
    const {error:leaveError}=await db.current!.from("employee_leave_entitlements").insert(entitlements);setSaving(false);element.reset();setType("probationary");setMessage(leaveError?`Employee saved; leave setup needs attention: ${leaveError.message}`:"Employee details and entitlements saved.");await load(db.current!,org);
  }

  return <main className="admin-page"><header className="admin-top"><div className="brand login-brand"><b>P</b> PulseHR</div><div><a href="/">Dashboard</a><a href="/attendance">Attendance</a><a href="/reports">Reports</a></div></header><div className="employee-master admin-content">
    <div className="admin-title"><small>PEOPLE ADMINISTRATION</small><h1>Employee master</h1><p>Employment terms, alerts, leave entitlements, payroll setup, and government benefits.</p></div>{message&&<div className="login-message">{message}</div>}
    {alerts.length>0&&<section className="alert-panel card"><h2>Upcoming employment actions</h2><div className="alert-list">{alerts.map(a=><div key={a.employee_id}><b>{a.full_name}</b><span>{a.alert_type==="regularization"?"Regularization review":"Contract renewal"} · {a.due_date}</span><em className={a.days_remaining<0?"late":""}>{a.days_remaining<0?`${Math.abs(a.days_remaining)} days overdue`:`${a.days_remaining} days left`}</em></div>)}</div></section>}
    <section className="employee-layout"><form className="card employee-form" onSubmit={addEmployee}><div className="form-title"><h2>Add complete employee record</h2><p>Required fields drive attendance and employment alerts.</p></div>
      <fieldset><legend>Identity and contact</legend><div className="form-grid"><label>Full name<input name="full_name" required/></label><label>Employee ID<input name="employee_number" required/></label><label>Email<input name="email" type="email"/></label><label>Mobile number<input name="mobile_number"/></label><label>Birth date<input name="birth_date" type="date"/></label><label>Initial kiosk PIN<input name="pin" type="password" inputMode="numeric" pattern="[0-9]{4,8}" required/></label><label className="wide">Address<textarea name="address"/></label></div></fieldset>
      <fieldset><legend>Employment and pay</legend><div className="form-grid"><label>Department<input name="department"/></label><label>Position<input name="position_title"/></label><label>Hire/start date<input name="hire_date" type="date" required value={hireDate} onChange={e=>setHireDate(e.target.value)}/></label><label>Classification<select name="employment_type" value={type} onChange={e=>setType(e.target.value)}><option value="probationary">Probationary</option><option value="regular">Regular</option><option value="fixed_term">Fixed-term contract</option></select></label>{type==="probationary"&&<div className="calculated wide">Regularization review: {hireDate?addMonths(hireDate,policy.probation_months):`after ${policy.probation_months} months`}</div>}{type==="fixed_term"&&<label>Contract term<select value={contractMonths} onChange={e=>setContractMonths(Number(e.target.value))}>{policy.contract_term_options.map(m=><option key={m} value={m}>{m} months</option>)}</select></label>}<label>Pay frequency<select name="pay_frequency" defaultValue={policy.default_pay_frequency}><option value="weekly">Weekly</option><option value="semi_monthly">Semi-monthly</option><option value="monthly">Monthly</option></select></label><label>Rate basis<select name="rate_type"><option value="monthly">Monthly</option><option value="weekly">Weekly</option><option value="daily">Daily</option><option value="hourly">Hourly</option></select></label><label>Basic rate (PHP)<input name="basic_rate" type="number" min="0" step="0.01"/></label></div></fieldset>
      <fieldset><legend>Philippine benefits</legend><div className="benefit-grid"><label><input type="checkbox" name="thirteenth_month_enabled" defaultChecked/> 13th-month pay</label><label><input type="checkbox" name="sss_enabled" defaultChecked/> SSS</label><label><input type="checkbox" name="philhealth_enabled" defaultChecked/> PhilHealth</label><label><input type="checkbox" name="pagibig_enabled" defaultChecked/> Pag-IBIG</label></div><div className="form-grid ids"><label>SSS number<input name="sss_number"/></label><label>PhilHealth number<input name="philhealth_number"/></label><label>Pag-IBIG MID<input name="pagibig_number"/></label><label>TIN<input name="tin_number"/></label></div><p className="legal-note">Statutory benefits are enabled by default. Disable only with a documented lawful exclusion.</p></fieldset>
      <fieldset><legend>Leave entitlements</legend><div className="leave-grid">{leaves.map(([code,name,days,kind])=><div key={code}><label><input type="checkbox" name={`enable_${code}`} defaultChecked={type==="regular"||kind==="statutory_event"}/> {name}</label>{kind==="annual_credit"?<input aria-label={`${name} days`} name={`leave_${code}`} type="number" min="0" step="0.5" defaultValue={days}/>:<span>Eligibility-based</span>}</div>)}</div></fieldset><button className="primary save-employee" disabled={saving}>{saving?"Saving employee…":"Save employee record"}</button>
    </form><aside className="policy-side card"><h2>Dynamic defaults</h2><p>Applied to new employees; existing agreed terms are preserved.</p><form onSubmit={savePolicy}><label>Probation period<select name="probation_months" defaultValue={policy.probation_months}>{[1,2,3,4,5,6].map(m=><option key={m} value={m}>{m} month{m>1?"s":""}</option>)}</select></label><label>Contract choices<input name="contract_terms" defaultValue={policy.contract_term_options.join(",")}/><small>Months, comma-separated</small></label><label>Default pay frequency<select name="default_pay_frequency" defaultValue={policy.default_pay_frequency}><option value="weekly">Weekly</option><option value="semi_monthly">Semi-monthly</option><option value="monthly">Monthly</option></select></label><button className="primary">Save defaults</button></form><div className="policy-warning"><b>Legal guardrail</b><p>Probation is capped at six months. Contribution tables will be effective-dated in the payroll phase.</p></div></aside></section>
    <section className="card admin-table employee-list"><div className="section-head"><div><h3>Employees</h3><p>{employees.length} records</p></div><input className="table-search" placeholder="Search name, ID, department" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="employee-master-tr head"><span>Employee</span><span>Role</span><span>Classification</span><span>Pay schedule</span><span>Next action</span></div>{employees.filter(e=>`${e.full_name} ${e.employee_number} ${e.department||""}`.toLowerCase().includes(query.toLowerCase())).map(e=><div className="employee-master-tr" key={e.id}><span><b>{e.full_name}</b><small>{e.employee_number}</small></span><span>{e.position_title||"—"}<small>{e.department||"Unassigned"}</small></span><span className="status-chip">{e.employment_type.replace("_"," ")}</span><span>{e.pay_frequency.replace("_","-")}</span><span>{e.regularization_due_date||e.contract_end_date||"No scheduled review"}</span></div>)}</section>
  </div></main>;
}
